name: Build Docker
permissions:
  contents: read
  packages: write
jobs:
  docker-build:
    outputs:
      digest: ${{ steps.docker_variant.outputs.digest }}
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.3
      with:
        submodules: recursive
    - name: Get release version string
      run: |
        echo "long=$(./bin/buildinfo.py long)" >> $GITHUB_OUTPUT
      id: version
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
      with:
        cache-image: true
    - name: Docker setup
      uses: docker/setup-buildx-action@v4
      with:
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io", "public.ecr.aws"]
    - name: Sanitize platform string
      id: sanitize_platform
      run: echo "cleaned_platform=${{ inputs.platform }}" | sed 's/\//_/g' >> $GITHUB_OUTPUT
    - name: Docker login
      if: ${{ inputs.push }}
      uses: docker/login-action@v4
      with:
        username: meshtastic
        password: ${{ secrets.DOCKER_FIRMWARE_TOKEN }}
    - name: Docker tag
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: meshtastic/meshtasticd
        tags: |
          GHA-${{ steps.version.outputs.long }}-${{ inputs.distro }}-${{ steps.sanitize_platform.outputs.cleaned_platform }}
        flavor: latest=false
    - name: Docker build and push
      uses: docker/build-push-action@v7
      id: docker_variant
      with:
        context: .
        file: |
          ${{ contains(inputs.distro, 'debian') && './Dockerfile' || contains(inputs.distro, 'alpine') && './alpine.Dockerfile' }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        platforms: ${{ inputs.platform }}
        build-args: |
          PIO_ENV=${{ inputs.pio_env }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
env:
  GERALT_SECRET: ${{ secrets.GERALT }}
on:
  workflow_call:
    secrets:
      DOCKER_FIRMWARE_TOKEN:
        required: false
    inputs:
      distro:
        description: Distro to target
        required: true
        type: string
      platform:
        description: Platform to target
        required: true
        type: string
      runs-on:
        description: Runner to use
        required: true
        type: string
      push:
        description: Push images to registry
        required: false
        type: boolean
        default: false
      pio_env:
        description: PlatformIO environment to build
        required: false
        type: string
        default: native
    outputs:
      digest:
        description: Digest of built image
        value: ${{ jobs.docker-build.outputs.digest }}
